import * as v from 'valibot';

export const BaseEnvironmentSchema = v.object({
  CALL_RETRIES: v.optional(v.string()),
  DD_API_KEY: v.string(),
  FAIL_ATTEMPTS: v.optional(v.string()),
  FDMS_VERSION: v.string(),
  GLIA_AI_MAX_TOKENS: v.string(),
  GLIA_AI_MODEL: v.string(),
  GLIA_AI_STOP_SEQUENCES: v.string(),
  GLIA_AI_TEMPERATURE: v.string(),
  GLIA_API_DOMAIN: v.string(),
  GLIA_KV_STORAGE_REPOSITORY: v.string(),
  GLIA_LIVE_OPERATOR_QUEUE: v.string(),
  GLIA_USER_API_KEY: v.string(),
  GLIA_USER_API_KEY_SECRET: v.string(),
  GOAL_ALREADY_AUTHENTICATED: v.string(),
  GOAL_ENTER_A_PIN: v.string(),
  GOAL_ENTER_OTP_CODE: v.string(),
  GOAL_FORGOT_PIN: v.string(),
  GOAL_INVALID_MEMBER_NUMBER: v.string(),
  GOAL_INVALID_OTP: v.string(),
  GOAL_INVALID_OTP_IDENTIFIER: v.string(),
  GOAL_INVALID_PIN: v.string(),
  GOAL_NEED_TO_AUTHENTICATION: v.string(),
  GOAL_OTP_FLOW_START: v.string(),
  GOAL_PIN_ATTEMPTS_EXCEEDED: v.string(),
  GOAL_SUCCESSFULLY_VERIFIES_MEMBER_NUMBER_AND_PIN: v.string(),
  GOAL_TRANSFER_TO_LIVE_OPERATOR: v.string(),
  GOAL_ZERO_PRESS: v.string(),

  INPUT_VALIDATION_FAILED_ATTEMPTS: v.optional(v.string()),
  INPUT_VALIDATION_FAILED_ATTEMPTS_LIMIT: v.optional(v.string()),

  IS_DEV_MOD: v.optional(v.string()),
  LYNKTEK_API_DOMAIN: v.string(),
  LYNKTEK_API_HEADER: v.string(),
  LYNKTEK_DEFAULT_PIN: v.optional(v.string()),
  PROMPT_DETECT_CONFIDENCE: v.string(),
  PROMPT_OPTION_DETECTOR: v.string(),
  REQUEST_TIMEOUT: v.optional(v.string()),
  RETRY_DELAY: v.optional(v.string()),
  SITE_ID: v.string(),
  VALIDATE_OTP_IDENTIFIER: v.union([v.literal('SOCIAL_SECURITY_NUMBER'), v.literal('ACCOUNT_NUMBER'), v.literal('CARD_NUMBER')]),
});
